### PR TITLE
Added Three columns on main section

### PR DESCRIPTION
**Pull request by TedLivist**
# Newsweek Clone using Bootstrap:

### In this milestone we added:
- Column 1 with the following headers: Featured stories and Sponsored insights / Rankings

- Column 2 with the following headers: Top story, My turn, Culture & travel, More stories and Latest news

- Column 3 which contains the following headers: The debate, Opinion, Sponsored insights / Rankings and Free signup

### CODE REVIEW

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
# Status: Change Requested

Good job so far guys @TedLivist  and @Mhdez221993 your project looks good but you need to make some changes in order to move on

## To Highlights image

- Project looks good on a mobile device
- Each image has a link
- Each title you used a hx tag
- Used semantic HTML

## To Improve image

- Use a simple and descriptive PR title
## Desktop
- It has 3 columns

Original

col

yours 

col1

- On a tablet it looks okay just this column

op
 try to make it look like the original

original

opinion

- On mobile fix just the footer

footer
 
original

footer1

## Kindly refer to the original while designing it will help you to user proper bootstrap classes and remember you still have 2 reviews only and work accordingly

## Happy Coding

Lydia Ingabire

**Comment by DeliceLydia** [comment]
## Desktop

desktop

## Tablet

tab

## Mobile

mobile
 
Please refer to these tables it can help

**Review by george-shammar — CHANGES_REQUESTED** [review]
**### STATUS: CHANGES REQUIRED**
Good job so far. Your effort is noteworthy. Please don't be tired. :muscle: 

Please see below outstanding changes yet to be implemented from the last review and that are considered mandatory. The optional requirements are not mandatory but nice to have.

- [x] Use meaningful names for your Pull Requests and add a summary of its content as described[ here.](https://microverse.zendesk.com/hc/en-us/articles/360055660814-Professional-GitHub-repository). Your pull request title is too ambiguous. Part of the title should form the summary of the PR message.


[OPTIONAL]

- [ ] You currently have over 400 lines in your style sheet which defeats the whole essence of using bootstrap CSS classes. Most of the styling used in the style sheet can be achieved with bootstrap. Please refactor the code in your style sheet and use more of bootstrap.
 

- [x] Please see my inline comment on the usage of !important rule.

Please implement the change and submit another CRR.

As described in the [Code reviews limit Policy,](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) , you have only 1 code review left for this project. If you think that the code review was not fair, you can request a second-opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s).

If you require further clarification or help, please reach out to me on slack @george gbenle

Happy coding.

**Review by descholar-ceo — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @Mhdez221993 and @TedLivist  , your project is approved :tada: :tada: :tada: 
You have implemented all requested changes from the previous review, so I am approving this project, it doesn't need more changes, you can go ahead and merge all of the changes on base branch,

Don't forget to fill the mandatory project completion form, and see you to next project,

Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Pull request merged**
